# Generated by Django 3.1.1 on 2020-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Image', models.TextField(max_length=400)),
                ('Source', models.TextField(max_length=400)),
                ('Ingredients', models.TextField(max_length=400)),
            ],
        ),
    ]
