# Generated by Django 3.1.1 on 2020-09-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='myRecipes',
        ),
    ]
