# Generated by Django 3.1.1 on 2020-09-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200920_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myRecipes',
            new_name='Recipe',
        ),
    ]
